### ISSUE TITLE
Disabling Zendesk Schedules doesn't work

### ISSUE THREAD

**Issue by bbirand** [fivetran/dbt_zendesk#10]
We don't use Schedules in Zendesk, so I set the variable `using_schedules` to `False`.

However, this package still doesn't compile, with the following error
```
Database Error in model stg_zendesk_ticket_schedule (models/stg_zendesk_ticket_schedule.sql)
  002003 (42S02): SQL compilation error:
  Object 'FIVETRAN_DATABASE.ZENDESK.TICKET_SCHEDULE' does not exist or not authorized.
  compiled SQL at target/run/zendesk_source/models/stg_zendesk_ticket_schedule.sql
```

The table `TICKET_SCHEDULE` in fact does not exist. Shouldn't setting the `using_schedules` make up for this?

**Comment by fivetran-kristin** [comment]
Hi @bbirand - can you please share a screenshot of your `dbt_project.yml` file for me to see how you've configured this?

Thanks!

**Comment by bbirand** [comment]
<img width="605" alt="image" src="https://user-images.githubusercontent.com/334435/107073377-4dfb7a00-67b5-11eb-9baa-181d38eacf2a.png">

**Comment by fivetran-kristin** [comment]
Ah, so you will need to also disable these models in the zendesk source model, as outlined [here](https://github.com/fivetran/dbt_zendesk#disabling-models).
```
vars:
  zendesk_source:
    using_schedules: false 
  zendesk:
    using_schedules: false
```


As an alternative, you can define this as a global variable, so that you don't need to repeat the configuration.  Here's an example of how to do that:

```
vars:
  using_schedules: false 
```

Keep me posted on how it goes! Good luck :)

**Comment by bbirand** [comment]
Ah got it! I knew I was missing something!

Shouldn't the `zendesk_source` variable point to the `zendesk` variable? I think that's how I missed this the first time around. Namely on this row: 
https://github.com/fivetran/dbt_zendesk_source/blob/010b1398a278eac952db68f21604eb6b1eb2cd1e/dbt_project.yml#L24

**Comment by fivetran-kristin** [comment]
Nice, happy that worked for you.

The `zendesk` package does have a dependency on the `zendesk_source` package so you're automatically using both if you use the `zendesk` package. 

However, we needed to declare variables in both, and the way dbt is configured requires us to specify the project name as so:
```
vars:
  zendesk_source: --- project name
    using_schedules: false 
  zendesk: --- project name
    using_schedules: false
```
We use the variable in both projects/packages, and therefore need to define for each.

If you want to chat further, our team hosts regular office hours.  You can book time with us using [this link](--- project name) :)
