### ISSUE TITLE
[Feature] Update dbt-date version range

### ISSUE THREAD

**Issue by kcraig-ats** [fivetran/dbt_zendesk#109]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

The version range for `calogica/dbt-date` in this package is out of sync with the current version range, `[">=0.9.0", "<0.10.0"]`. The version dependency prevents others from updating to the latest version.

### Describe alternatives you've considered

n/a

### Are you interested in contributing this feature?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during your [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance.
- [ ] No.

### Anything else?

[Link](https://github.com/calogica/dbt-date#install) to the package.

**Comment by fivetran-jamie** [comment]
Hey there @kcraig-ats! Thanks for opening this and for your continued engagement with the package 😄 This definitely makes sense to update, and everything appears to run smoothly locally with the updated dbt-date version range.

We are currently working on some other Zendesk issues that we could push this update out with in the coming weeks, but if you would like this update ASAP and are still interested in contributing, please feel free to open a PR! We'd happily prioritize reviewing and merging it in. Thanks!

**Comment by fivetran-reneeli** [comment]
Hey @kcraig-ats, thanks for raising this! This has been included in our latest [release ](https://github.com/fivetran/dbt_zendesk/releases/tag/v0.12.0) of the package and as such we'll be closing this out.
