### ISSUE TITLE
[Bug] Fivetran Zendesk package references an old status for on hold tickets

### ISSUE THREAD

**Issue by mpavillet** [fivetran/dbt_zendesk#112]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

See slack thread here for reference: https://getdbt.slack.com/archives/C01D1R2JLLA/p1695159048651189

The model `int_zendesk__requester_wait_time_filtered_statuses` looks for a status value = 'on-hold' . It turns out that this value doesn't exist in Zendesk. It is 'hold'.
 
https://github.com/fivetran/dbt_zendesk/blob/v0.11.2/models/sla_policy/requester_wait_time/int_zendesk__requester_wait_time_filtered_statuses.sql#L30

### Expected behavior

The filtered status looks for valid statuses in Zendesk, in this case, 'hold' instead of 'on-hold'

### dbt Project configurations

N/A

### Package versions

  - package: fivetran/zendesk
    version: 0.10.0 

### What database are you using dbt with?

snowflake

### dbt Version

1.3

### Are you willing to open a PR to help address this issue?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by fivetran-joemarkiewicz** [comment]
@mpavillet thank you for raising this issue with our team. We have been able to incorporate this update in the latest release of the dbt_zendesk package. You should be able to see the package accounting for the proper `hold` status in calculations.

As such, I will close this ticket. Please let us know if you see that this issue still persists after upgrading. Thank you!
