### ISSUE TITLE
[Feature] Update Zendesk SLA policies to look at historical agents

### ISSUE THREAD

**Issue by jackiexsun** [fivetran/dbt_zendesk#120]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

Currently the way the zendesk package calculates SLA policies is to check whether the user is an "agent" or "admin" role to meet the SLA. We are starting to deactivate former employees in Zendesk since they take up licenses so they won't be an "agent" or "admin" role anymore. This will retroactively impact our SLA policy calculations. Can we modify the package to use another way to determine if the user is an internal company user (like looking at the email domain) or enable the ability to use a zendesk user history table so we can see if the user was ever an "agent" or "admin"?

### Are you interested in contributing this feature?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during your [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance.
- [X] No.

**Comment by fivetran-joemarkiewicz** [comment]
Hey @jackiexsun I had planned to incorporate this into the current sprint, but had to deprioritize due to a different Zendesk ticket. I am planning to fold this into the upcoming sprint. We can chat with you further once someone from my team picks this up in the next sprint!

**Comment by cpmclaughlin** [comment]
@fivetran-joemarkiewicz I'm also very interested in this package handling former agents as agents rather than end users. Please apply this fix to reply times and resolution times as well as to SLAs. Would love to know when you'll be working on this and when to expect it to be resolved when possible. Thanks!

**Comment by fivetran-jamie** [comment]
@cpmclaughlin currently working on this! for your own case, would you only look at email domains, or would you want this additional internal-user criteria to be more flexible (ie reference other USER columns)?

**Comment by cpmclaughlin** [comment]
@fivetran-jamie so excited to hear that!!! More flexible internal-user criteria would be most helpful. Unfortunately, in our case email domain alone would not work. What I'd been considering using before I found that you all were about to work on this was 
```
where ((signature is not null and signature is distinct from '') or (alias is not null and alias is distinct from ''))
        and (restricted_agent = TRUE or suspended = TRUE)
        and (email ilike '%modernhealth%' or email is null)
```
Let me know if you have any additional questions and thank you for working on this!!! Will be incredibly helpful to us.

**Comment by cpmclaughlin** [comment]
@fivetran-jamie will I (or rather, my data eng counter part) be able to define the variable in using the fivetran quickstart data models or only if we were using the transformations for dbt core? Right now, we're only using the quickstart for this instance of zendesk because we're already using the transformations for dbt core for another instance we have. If the new variable you're working on only works with transformations for dbt core, is it possible to set that up for multiple instances now? I think I saw a ticket for that too at some point. Thanks!

**Comment by jackiexsun** [comment]
@fivetran-jamie yes I can test this out!

**Comment by fivetran-jamie** [comment]
@cpmclaughlin Darn yeah you would only be able to define the variables if using transformations with dbt core, not with Quickstart. 

But if the overall goal is to run the package on multiple zendesk instances, perhaps this [blog post](https://community.fivetran.com/t5/developer-forum/%EF%B8%8F-running-a-dbt-package-against-separate-schemas/m-p/51#M1) would be of use to you. 

We do have a couple of [tickets](https://github.com/fivetran/dbt_zendesk/issues/124) open to natively run the package on multiple sources and are heavily considering adding this functionality, but no firm timeline yet

**Comment by jackiexsun** [comment]
Hi @cpmclaughlin is this the criteria for identifying former agents that you landed on? I'm trying to do something similar for Fivetran, and got to 
```
where suspended and email like '%@fivetran.com'
```
but it's not 100% accurate. Wondering if you got to a more accurate criteria? I asked Zendesk support about this problem and they were not helpful :/ 

> @fivetran-jamie so excited to hear that!!! More flexible internal-user criteria would be most helpful. Unfortunately, in our case email domain alone would not work. What I'd been considering using before I found that you all were about to work on this was
> 
> ```
> where ((signature is not null and signature is distinct from '') or (alias is not null and alias is distinct from ''))
>         and (restricted_agent = TRUE or suspended = TRUE)
>         and (email ilike '%modernhealth%' or email is null)
> ```
> 
> Let me know if you have any additional questions and thank you for working on this!!! Will be incredibly helpful to us.

**Comment by fivetran-jamie** [comment]
this has been rolled out in [v0.10.1](https://github.com/fivetran/dbt_zendesk_source/releases/tag/v0.10.1) of the source package! as a minor change, the transform package should automatically pick it up! cc @cpmclaughlin
