### ISSUE TITLE
[Bug] Minutes in sla_policies can be inaccurate due to where rounding occurs

### ISSUE THREAD

**Issue by fivetran-reneeli** [fivetran/dbt_zendesk#135]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

The calculated elapsed minutes in the `zendesk__sla_policies` end model can be off by a minute or so.

For example, in our sample data, ticket 69 shows an sla_elapsed_time of 4 minutes. But if you take the difference, technically it's closer to 3 minutes.

`2023-10-06 20:39:58 UTC, 2023-10-06 20:43:11 UTC `

This is because in `int_zendesk__reply_time_combined` we [calculate](https://github.com/fivetran/dbt_zendesk/blob/7b29ae004aefe3e96281417cb1638588035b0091/models/sla_policy/reply_time/int_zendesk__reply_time_combined.sql#L111) the difference between timestamps using _minute_ as the grain, whereas in our other models we use seconds then divide by 60.

`dbt.datediff("sla_schedule_start_at", "agent_reply_at", 'minute')`

More examples in this [comment](https://github.com/fivetran/dbt_zendesk/pull/134#discussion_r1464102430) in https://github.com/fivetran/dbt_zendesk/pull/134. 

### Expected behavior

The difference between timestamps should display more accurately. Therefore, we should calculate on the _seconds_ grain and divide by 60 to derive minutes. This is what's presently done in our other models, so would help with standardization as well.

Finally, let's make sure this is the case for the rest of package.

### dbt Project configurations

na

### Package versions

na

### What database are you using dbt with?

bigquery

### dbt Version

na

### Are you willing to open a PR to help address this issue?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by fivetran-joemarkiewicz** [comment]
This has issue should now be addressed in the latest `v0.14.0` release of the dbt_zendesk package. As such, closing this out. 

Please feel free to reopen or create a new issue if the original issue persists following the upgrade.
