### ISSUE TITLE
[Bug] Not able to disable package model of dbt_packages/zendesk_source/models/tmp/

### ISSUE THREAD

**Issue by ba5413** [fivetran/dbt_zendesk#153]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

I am trying to disable dbt_packages/zendesk_source/models/tmp/stg_zendesk__group_tmp.sql using my root dbt_project.yml file. 

I have created my own version of stg_zendesk__group_tmp.sql in my main model directory, but not able to disable the package model; even though I have defined it correctly in my root dbt_project.yml file. ``

### Expected behavior

It should not run dbt package stg_zendesk__group_tmp model instead only run my main model folder stg_zendesk__group_tmp

### dbt Project configurations

```javascript
models:
  database: xxxx
  xxx_dbt:
    zendesk_source:
      models:
        stg_zendesk__group:
          +enabled: false
        tmp:  
          stg_zendesk__group_tmp:
            +enabled: false
```
I have tried so many combination but it doesn't work

### Package versions

- package: fivetran/zendesk
    version: [">=0.11.0", "<0.12.0"]

### What database are you using dbt with?

snowflake

### dbt Version

1.7

### Are you willing to open a PR to help address this issue?

- [X] Yes.
- [X] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by fivetran-jamie** [comment]
hey there @ba5413 -- have you tried this configuration? the only differences are that `zendesk_source` is not scoped under your `xxx_dbt` project and i've removed the second `models` bit
```yml
models:
  database: xxxx
  zendesk_source:
    stg_zendesk__group:
      +enabled: false
    tmp:  
      stg_zendesk__group_tmp:
        +enabled: false
```

**Comment by fivetran-jamie** [comment]
hey @ba5413 i'm going to close this issue for now as I'm fairly confident the above configuration will do the trick. Please feel free to reopen this issue if otherwise!
