### ISSUE TITLE
[Feature] Incoprorate Historical Schedule Changes 

### ISSUE THREAD

**Issue by fivetran-jamie** [fivetran/dbt_zendesk#158]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

Account for changes made to schedule start/end times by using the `audit_log` source table. Work has been started in https://github.com/fivetran/dbt_zendesk/pull/157 and https://github.com/fivetran/dbt_zendesk_source/pull/50 but the logic in the schedule_spine model needs to be updated to include the new code

### Are you interested in contributing this feature?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during your [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance.
- [ ] No.

**Comment by dkang1023** [comment]
@fivetran-jamie Hi Jamie, we are a Fivetran customer and looking to rely on this feature for critical business reporting. What's the current status of this, and are we able to get this prioritized? Let me know and thank you so much.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @dkang1023 we are actually committing to this as a feature update in our upcoming quarter (starting next week). I estimate we will have a working version ready by mid September.

**Comment by dkang1023** [comment]
Hi @fivetran-joemarkiewicz - I wanted to check-in here and confirm we should expect a fix in the upcoming weeks in September? Let me know and thanks again.

**Comment by fivetran-catfritz** [comment]
Hi @dkang1023 I will picking up this ticket, and the goal is to have this finished around the end of September!

**Comment by robabramowitz** [comment]
hi @fivetran-catfritz - I wanted to check in and see if you would be able to provide an estimated ETA on this. Thank you very much for all of the support!

**Comment by fivetran-catfritz** [comment]
Hi @robabramowitz thank you for checking in! And good timing--I am currently working on this and hope to have a test branch available in the next couple days.

**Comment by fivetran-catfritz** [comment]
Hi @dkang1023 and @robabramowitz I have created a test branch with the updates to bring in historical schedules. 

If you would like to install it and try it out, you can add the following code in place of the existing zendesk in your packages.yml.

```yml
- git: https://github.com/fivetran/dbt_zendesk.git
  revision: feature/historical-schedules
  warn-unpinned: false
 ```

Let me how this works for you! If things are working out, this will move on to release.

**Comment by dkang1023** [comment]
@fivetran-catfritz Thank you - we are doing validation checks on our end. I see that it has already been pushed to release, so we will follow up with our findings. Thank you for the patience.

**Comment by fivetran-joemarkiewicz** [comment]
This update has since been rolled out in the latest version of the package. As such, I will close out this issue.
