### ISSUE TITLE
[Bug] Adjust `first_reply_time` SLA policy logic to include first SLA Policy where target was met, or the most recently applied policy

### ISSUE THREAD

**Issue by fivetran-jamie** [fivetran/dbt_zendesk#179]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

So in the `zendesk__sla_policies` model, for `first_reply_time` metrics, we include the most recently applied SLA policy for each ticket. This is what Zendesk does as well **UNLESS** the first reply time target was met for the first/earlier SLA policy. In that case, the SLA policy that was met has its metric reported. The package does not take whether or not the policy target was met into account, specifically on this [line](https://github.com/fivetran/dbt_zendesk/blob/main/models/sla_policy/int_zendesk__sla_policy_applied.sql#L32) 

The package should match Zendesk's reporting behavior.

### Relevant error log or model output

```shell
Most recent `first_reply_time` metric is returned
```

### Expected behavior

Most recent met `first_reply_time` metric is returned, otherwise most recent `first_reply_time` metric

### Possible solution

This [logic](https://github.com/fivetran/dbt_zendesk/blob/main/models/sla_policy/int_zendesk__sla_policy_applied.sql#L32) that determines which `first_reply_time` record we grab is updated to somehow include whether the target was met for `first_reply_time` metrics. 

We would need to compare the[`sla_breach_at`](https://github.com/fivetran/dbt_zendesk/blob/main/models/sla_policy/reply_time/int_zendesk__reply_time_calendar_hours.sql#L12-L18) (this is pretty complicated in the [business hours](https://github.com/fivetran/dbt_zendesk/blob/main/models/sla_policy/reply_time/int_zendesk__reply_time_business_hours.sql#L177-L180) model however) to the [first agent reply](https://github.com/fivetran/dbt_zendesk/blob/main/models/sla_policy/reply_time/int_zendesk__reply_time_combined.sql#L72-L82) (if there is one)

Given how complicated the calculation for `sla_breach_at` in business hours is, I wonder if we should leave all `first_reply_time` records in `int_zendesk__sla_policy_applied` (with the current `latest_sla` flag included but not used to filter), and choose our winning `first_reply_time` record in the end model or something.

### dbt Project configurations

NA

### Package versions

latest

### What database are you using dbt with?

postgres, redshift, snowflake, bigquery, databricks

### How are you running this dbt package?

Fivetran Quickstart Data Model, Fivetran Transformations, dbt Core™, dbt Cloud™

### dbt Version

latest

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [ ] Yes, but I will need assistance.
- [ ] No.

**Comment by fivetran-avinash** [comment]
After debugging with @fivetran-jamie , we've decided not to proceed forward with this issue. 

The production data is matching the Zendesk UI report. You can see the ticket id, the SLA Policy Name, the SLA elapsed time all matching up. So currently it seems the reporting is fine based off the ticket cases we accounted for.

 The initial assumption was that `first_reply_time` would be created for every `sla_policy` (which would then lead to the most recent SLA policy being grabbed), but it seems when looking at the `ticket_field_history`, that is not the case when a ticket is solved initially. It only creates a first reply time for the sla policy which was met, but not for the SLA Change later on. Without that, the joins in the `int_zendesk__sla_policy_applied` model will only take in the Email SLA as in the report, so it’s working as expected.
​
If any other issues arise, we will reopen this issue.
