### ISSUE TITLE
"Business Minute" metrics don't take into account daylight savings

### ISSUE THREAD

**Issue by austin-home** [fivetran/dbt_zendesk#25]
Hi there,

I'm hope I'm missing something, but it appears this package doesn't include Fivetran's `DAYLIGHT_TIME` and `TIME_ZONE` tables, when converting `SCHEDULES` from UTC. I've noticed after some QA on tickets created before the most recent daylight savings time, that historical business minute calculations appear to be based off the _current_ date's time zone offset. 

I'm referring to these tables from the Fivetran release notes, which I didn't see in this repo:
![Screenshot 2021-04-07 at 13 24 30](https://user-images.githubusercontent.com/72866398/113859001-b01c2f80-97a4-11eb-8de7-5715b6768b9c.png)

Am I mistaken? Any help here is really appreciated.

**Comment by fivetran-kristin** [comment]
Hey @austin-home, this package was designed to only use times that are in UTC for all calculations.  We don't make use of the daylight time or any timezone offset fields.

Can you confirm whether the ticket_field_history.updated field (from your raw Fivetran data) is in UTC?

**Comment by austin-home** [comment]
Hi @fivetran-kristin - confirmed that field is in UTC.

Doesn't this potentially affect all business minute metrics (not within the current date's time zone offset)? This is important for us because we have 60 minute SLAs which now seem incorrectly calculated if their timestamps overlap with the beginning or end of local time business hours. Do you know how others are dealing with this?

**Comment by fivetran-kristin** [comment]
This is the first time this has been brought to my attention, so I'm not sure if others are experiencing this issue.

My understanding is that this shouldn't be a problem because we are using UTC times across all calculations.  

Do you want to set up some time to talk and dig into a specific example of where this is happening together?  I think that'll be the best way to troubleshoot.

Book some time here: http://5tran.co/office-hours

**Comment by austin-home** [comment]
Hey @fivetran-kristin,

While creating a specific example for us to troubleshoot, I think I've confirmed that you're right. I'll close for now, sorry for the false alarm!
