### ISSUE TITLE
Compilation fails for snowflake destinations

### ISSUE THREAD

**Issue by JosephGoelz** [fivetran/dbt_zendesk#3]
When I attempt to run the zendesk_ticket_metrics model and all upstream models
dbt run -m +zendesk_ticket_metrics

The job fails with the following error

Database Error in model stg_zendesk_group (models/stg_zendesk_group.sql)
  001003 (42000): SQL compilation error:
  syntax error line 5 at position 33 unexpected 'group'.
  syntax error line 7 at position 0 unexpected ')'.
  compiled SQL at target/run/zendesk_source/models/stg_zendesk_group.sql

This is because the keyword **group** isn't escaped with quotes causing issues in snowflake.
Locally I was able to get it to run by modifying the src_zendesk.yml file
to include an identifier which allowed the variable lookup to produce properly formatted snowflake sql.

        - name: group
        **identifier: '"GROUP"'**
        description: >
          When support requests arrive in Zendesk Support, they can be assigned to a Group. Groups serve as the core
          element of ticket workflow; support agents are organized into Groups and tickets can be assigned to a Group
          only, or to an assigned agent within a Group. A ticket can never be assigned to an agent without also being 
          assigned to a Group.
        freshness: null
        columns:
          - name: id
            description: Automatically assigned when creating groups
            tests:
                - unique
                - not_null 
          - name: name
            description: The name of the group

I am unable to test if this will cause issues with other warehouse destinations (ie Redshift, etc)

**Comment by fivetran-kristin** [comment]
@JosephGoelz thanks for letting us know! I'll look into how to fix this and push an update soon.

Did you run into any other errors, or were you able to successfully get the package to run after modifying the `src_zendesk.yml` file locally?

**Comment by JosephGoelz** [comment]
Everything looked good apart from this one issue, thank you

**Comment by fivetran-kristin** [comment]
@JosephGoelz I have a fix for this, yet haven't pushed it to master yet.  I've tested on my side, but can you please test as well to make sure it works on your side?  The fix has been pushed to our zendesk source package, on branch fix_keyword.  Please install only that package and see if it runs without error.  Thanks!

```
packages:

  - git: https://github.com/fivetran/dbt_zendesk_source.git
    revision: fix_keyword
    warn-unpinned: false
```

**Comment by JosephGoelz** [comment]
This worked! Everything ran without an error.

**Comment by fivetran-kristin** [comment]
Great, thanks for testing! I'll create a new release for this fix soon.

**Comment by JosephGoelz** [comment]
Hello, following up.
Will the fix be released soon?

**Comment by fivetran-kristin** [comment]
We're working on a couple other improvements to include in this release. It should be ready early next week.

**Comment by jeffthink** [comment]
Hey folks - I also have this same issue with Snowflake. Is it possible to get a minor fix version bump with the change so that we can use this package?

Thanks!

**Comment by fivetran-kristin** [comment]
we're in the process of publishing our new releases.  You'll be able to upgrade soon! Thanks for the patience :)

**Comment by fivetran-kristin** [comment]
Please upgrade to the latest version, which fixes this issue.

```
packages:
  - package: fivetran/zendesk
    version: 0.1.1
```
