### ISSUE TITLE
QUESTION - Zendesk__ticket_backlog not working because of invalid identifier ASSIGNEE_ID

### ISSUE THREAD

**Issue by jordstew** [fivetran/dbt_zendesk#30]
**Are you a Fivetran customer?** 
Yes. Jordan Stewart. Sr Data Engineer. Workrise

**Your Question**
We have been using the Zendesk and Zendesk Source dbt hub packages since the first version was released. We now are trying to upgrade to the newest Zendesk package version, as two new tables are available and we would like to be up to date in general with these packages.

Our issue is with building the new Zendesk__ticket_backlog table/model. It is failing for this:

```
Database Error in model zendesk__ticket_backlog (models/zendesk__ticket_backlog.sql)
  000904 (42000): SQL compilation error: error line 644 at position 35
  invalid identifier 'TICKET_FIELD_HISTORY.ASSIGNEE_ID'
  compiled SQL at target/run/zendesk/models/zendesk__ticket_backlog.sql
```
I see that the data in the field_name column from the stg_zendesk_ticket_field_history is pivoted when the value is 'priority', 'assignee_id' or 'status' which is how the assignee_id column is created. This CTE here, __dbt__CTE__int_zendesk__field_history_pivot, returns the assignee_id column and looks great.

However, in this CTE, '__dbt__CTE__int_zendesk__field_history_scd' only 3 columns are returned ,  
date_day as valid_from, 
        ticket_id,
        ticket_day_id.

This CTE is then used going forward to further build out the ticket_field_history CTE and alias that is used in the final join where our code is failing:      

--Join not needed if fields is not located in variable, otherwise it is included.
    left join users as assignee
        on assignee.user_id = cast(ticket_field_history.assignee_id as 
    bigint
)

We have no variables set in our dbt_project.yml, so we are using all default values as defined in the dbt hub Zendesk documentation. 

I am confused how this package is intended to work out of the box with no manual code changes or variables set, as the assigne_id column is clearly dropped out after the __dbt__CTE__int_zendesk__field_history_scd CTE is created and referenced forward. I see no bugs or issues about this, and this code clearly works for other people who are using it or else there would be open issues. But at a loss for how to get this working without changing the code. 

**Additional context**
We use Snowflake as our data target

**Please indicate the level of urgency and business impact of this request** 
This is medium urgency and impact. Tracking our ticket backlog is something we don't currently have in place in the data warehouse, and this would be a great insight for our ops team.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @jordstew thanks for opening this Question! I am sorry to hear you have run into an error on the `zendesk__ticket_backlog` model.

This package is intended to run without variable configuration (apart from possibly disabling models if you do not have the table), which is strange to see you are running into an error like this. I just tested this quickly on my end to ensure my models would succeed without variable config and it succeeded with a full refresh run. Have you tried running your package with `dbt run --full-refresh` as this may do the trick?

**Comment by jordstew** [comment]
Hey @fivetran-joemarkiewicz , that does not work, still same error: 

Completed with 1 error and 0 warnings:

Database Error in model zendesk__ticket_backlog (models/zendesk__ticket_backlog.sql)
  000904 (42000): SQL compilation error: error line 644 at position 35
  invalid identifier 'TICKET_FIELD_HISTORY.ASSIGNEE_ID'
  compiled SQL at target/run/zendesk/models/zendesk__ticket_backlog.sql

When I look at the compiled code, like I described in my first post, it is clear why this is erroring and not working. I have no custom variables in my dbt_project.yml file besides this:

```
vars:
  zendesk_schema: ZENDESK_SUPPORT_SECURE
  zendesk_database: RAW
  zendesk_source:
    using_schedules: false
    group: "{{ source('zendesk', 'group_') }}"        # Disable if you do not have the schedule and ticket_schedule tables, or if you do not want metrics reported in business hours    # Disable if you are not using SLAs 
  zendesk:
    using_schedules: false
```
reason for the group in the zendesk_source variable is because we have to recreate it as GROUP_ because group is a reserved word in snowflake and it does not work when have a table simply named group, as it thinks we are doing a group by.

Any other ideas, Joe?

**Comment by fivetran-joemarkiewicz** [comment]
Hmm my variable config looks very similar to yours, but I am unable to replicate the error. Would you be able to clarify which version of the package you are using?

Looking at your past comments I noticed the models are CTE's, whereas for me they are materializing as tables. I also see your error line for the backlog model is at line 644, while my backlog model target only contains ~70 lines?

**Comment by jordstew** [comment]
Would it help if I sent you the compiled query for reference? I am using version 0.4.1

**Comment by fivetran-joemarkiewicz** [comment]
As it seems the compiled query is extremely long, I feel it would probably be best if we would be able to debug this live.

You can schedule some time to chat with myself and members of our team on our [Calendly](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours?month=2021-05) link for Thursday so we can debug live and hopefully get the package running successfully for you! Let me know if you have any questions.

**Comment by jordstew** [comment]
Hey Joe I figured it out. So for the first version of zendesk hub and zendesk source hub, we did the following in our dbt_project.yml:

```
  zendesk:
    #+database: EDW
    #+schema: ZENDESK_SECURE
    +database: DE_SANDBOX
    +schema: JSTEW
    +materialized: ephemeral
    zendesk_sla_breach:
      +materialized: table
    zendesk_ticket_enriched:
      +materialized: table
    zendesk_ticket_field_history:
      +materialized: table
    zendesk_ticket_metrics:
      +materialized: table
    zendesk__ticket_summary:
      +materialized: table
    zendesk__ticket_backlog:
      +materialized: table
    
  zendesk_source:
    #+database: EDW
    #+schema: ZENDESK_STG_SECURE
    +database: DE_SANDBOX
    +schema: JSTEW
    +materialized: table
```

we did this because we want the models to be materialized as tables instead of views. this worked for the first version of the zendesk hub, but now having this line about all other materializations being ephemeral seemed to break it:

```
  zendesk:
    #+database: EDW
    #+schema: ZENDESK_SECURE
    +database: DE_SANDBOX
    +schema: JSTEW
    **+materialized: ephemeral**
```


having this works:
```
  zendesk:
    #+database: EDW
    #+schema: ZENDESK_SECURE
    +database: DE_SANDBOX
    +schema: JSTEW
    #+materialized: ephemeral
    zendesk_sla_breach:
      +materialized: table
    zendesk_ticket_enriched:
      +materialized: table
    zendesk_ticket_field_history:
      +materialized: table
    zendesk_ticket_metrics:
      +materialized: table
    zendesk__ticket_summary:
      +materialized: table
    zendesk__ticket_backlog:
      +materialized: table
```

Thanks for the help, Joe. You can close this and cancel our working session, and I will also decline it.

**Comment by fivetran-joemarkiewicz** [comment]
That's great to hear you were able to get the package to work with the materialization update to the some of those intermediate models. 

That also explains the large compile code length. Thanks again for opening this issue and for letting us know you were able to come to a resolution, as such I will close this issue.
