### ISSUE TITLE
Reply/resolution times in business hours not matching up with Zendesk

### ISSUE THREAD

**Issue by prestonhsiao** [fivetran/dbt_zendesk#4]
When comparing reply/resolution times in business hours from the zendesk_ticket_metrics model to those in Zendesk Explore or the Zendesk Support API, the metrics do not match for the majority of tickets. 

A couple of issues:
1. Time in business hours is calculated in both dbt and Zendesk, but does not match
2. Time in calendar and business hours is calculated in Zendesk, but time in business hours is null in dbt

Is fivetran planning to add the ticket_metrics table from the Zendesk Support API? A direct connection would be great to have, as Zendesk provides these business hour metrics.

**Comment by fivetran-kristin** [comment]
Hi @prestonhsiao thanks for this info.  This is very interesting to hear. Can you please provide me some examples of times when this isn't calculating correctly? I'd love to dig in further... perhaps we can get on a call and troubleshoot together?  You can book time with me here: http://5tran.co/office-hours

**Comment by prestonhsiao** [comment]
Hi @fivetran-kristin I just booked a time for next week. In the meantime, here are some examples (**zendesk** being a direct export from Zendesk Explore, and **dbt** being from the dbt zendesk_ticket_metrics model):

### 1. Mismatching dbt first reply time (hrs) business hours 

- zendesk first reply time (hrs) calendar hours: 90.01
- zendesk first reply time (hrs) business hours: 53.8
- dbt first reply time (hrs) calendar hours: 90.01
- dbt first reply time (hrs) business hours: 41.7
### 2. NULL dbt first reply time (hrs) business hours 

- zendesk first reply time (hrs) calendar hours: 3.83
- zendesk first reply time (hrs) business hours: 0.033
- dbt first reply time (hrs) calendar hours: 3.83 
- dbt first reply time (hrs) business hours: NULL

### 3. Mismatching dbt first reply time (hrs) calendar and business hours
- zendesk first reply time (hrs) calendar hours: 2.15
- zendesk first reply time (hrs) business hours: 2.15
- dbt first reply time (hrs) calendar hours: 313.43
- dbt first reply time (hrs) business hours: 105.23

Happy to continue the conversation here before our call.

**Comment by fivetran-kristin** [comment]
@prestonhsiao thanks. It's going to be a little hard for me to dig in without access to your data. I can open some additional availability for this week if you'd like to meet earlier than this coming Monday. Let me know what time/date works for you and I'll try to accommodate.

**Comment by prestonhsiao** [comment]
@fivetran-kristin thank you for trying to accommodate! Would you have a 30 min time block from 10 - 5 on Wednesday or 12 - 5 on Thursday?

**Comment by fivetran-kristin** [comment]
Yeah, of course. Would love to figure out what's going on here asap.  I rescheduled our mtg to 10:30am on Wednesday.

**Comment by fivetran-kristin** [comment]
Discussed what is going on here and Preston is happy using the logic in the package.  Will consider adding both options in the future, however I'm going to close this issue for now.
