### ISSUE TITLE
BUG - reply_time fields in ticket_metrics not populating

### ISSUE THREAD

**Issue by emiliedecherney** [fivetran/dbt_zendesk#49]
**Are you a current Fivetran customer?** 
<Yes, Emilie DeCherney, Director of Analytics, Pendo>

**Describe the bug**
<First reply times not accurately logged in zendesk__ticket_metrics.first_reply_time_calendar_minutes and zendesk__ticket_metrics.first_reply_time_business_minutes for tickets where there is a clear response shown in the Zendesk UI>

**Steps to reproduce**
Run example query: 
select ticket_id, total_agent_replies, first_reply_time_business_minutes, first_reply_time_calendar_minutes
from `pendo-reporting.pendo_zendesk.zendesk__ticket_metrics`
where ticket_id = 75162

**Expected behavior**
Reply times to be populated

**Project variables configuration**

```name: 'analytics'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"


# Model Configuration
# Full documentation: https://docs.getdbt.com/docs/configuring-models
models:
    +persist_docs: # Create BigQuery descriptions for objects with resource descriptions.
        relation: True
        columns: True
    analytics:
     # Applies to all Files under models/temp
        materialized: table
        intermediate:
            dataset: staging
        final:
            dataset: final
        staging:
            schema: staging
        views:
            schema: views
        temp:
            schema: temp
    jira_source:
        +schema: staging
    jira:
        +schema: fivetran_jira
        intermediate:
            +schema: staging
    zendesk_source:
        +schema: staging
    zendesk:
        +schema: pendo_zendesk
        agent_work_time:
            +schema: staging
        intermediate:
            +schema: staging
        reply_times:
            +schema: staging
        sla_policy:
            +schema: staging
        ticket_history:
            +schema: staging
        utils:
            +schema: staging
    salesforce_source:
        +schema: staging
    salesforce:
        +schema: fivetran_salesforce
        intermediate:
            +schema: staging

vars:
    jira_schema: fivetran_jira
    jira:
        issue_field_history_columns: [
            "timespent",
            "assignee",
            "lastViewed",
            "summary",
            "resolutiondate",
            "creator",
            "resolution",
            "updated",
            "description",
            "timeoriginalestimate",
            "issuekey",
            "timeestimate",
            "security",
            "parent",
            "priority",
            "created",
            "workratio",
            "statuscategorychangedate",
            "statuscategory",
            "environment",
            "project",
            "issuetype",
            "reporter",
            "components",
            "labels",
            "versions",
            "fixVersions",
            "customfield_12602",  # The custom field for zendesk ticket count
            "customfield_12735", # one of the 'severity' fields
            "customfield_12100", #another 'severity' field
            "customfield_10114", # 'Team'
            "customfield_12801", # 'Team name'
            "customfield_11201", # 'Dev team'
            "customfield_12720", # 'Team'
            "customfield_12760", # 'Value proposition'
            "customfield_12508", # 'Buisness value'
            "customfield_12836" # 'Dev SOC Trust values'
        ]
    zendesk_schema: pendo_zendesk
    salesforce_schema: fivetran_salesforce
    fivetran_log:
        fivetran_log_using_transformations: false # this will disable all transformation + trigger_table logic
        fivetran_log_using_triggers: false # this will disable only trigger_table logic

```

**Package Version**

```packages:
  - package: fivetran/jira_source
    version: 0.2.0
  - package: fivetran/jira
    version: 0.3.0
  - package: fivetran/zendesk_source
    version: 0.3.0
  - package: fivetran/zendesk
    version: 0.4.0
  - package: fivetran/salesforce_source
    version: 0.2.1
  - package: fivetran/salesforce
    version: 0.3.1
  - package: fivetran/fivetran_log
    version: 0.3.0
```

**Warehouse**

 
- [X] BigQuery
- [ ] Redshift
- [ ] Snowflake
- [ ] Postgres
- [ ] Databricks
- [ ] Other (provide details below)

**Additional context**

**Screenshots**

Query results from zendesk__ticket_metrics for example ticket_id (75162) show null reply times, when there is a reply:
![image](https://user-images.githubusercontent.com/83296448/136208622-814b0bc8-4c2c-4684-a12f-d4ffaf383e22.png)

For the same ticket, reply is shown in Zendesk UI:
![image](https://user-images.githubusercontent.com/83296448/136213176-12235808-cdda-4ebf-a258-3fc4c3697243.png)

**Please indicate the level of urgency** 
Urgent, this is blocking ability to report accurately through several dashboards for an extended period of time.

**Are you interested in contributing to this package?** 

- [ ] Yes, I can do this and open a PR for your review.
- [ ] Possibly, but I'm not quite sure how to do this. I'd be happy to do a live coding session with someone to get this fixed. 
- [X] No, I'd prefer if someone else fixed this.  I don't have the time and/or don't know what the root cause of the problem is.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @emiliedecherney my appologies I missed the fivetran_log upgrade since `v0.3.0` uses the old version as well.
```yml
  - package: fivetran/jira
    version: 0.3.0
  - package: fivetran/zendesk ##Updated to the latest dbt v0.19.0 compatible release
    version: 0.5.2
  - package: fivetran/salesforce
    version: 0.3.1
  - package: fivetran/fivetran_log
    version: 0.3.2
```

**Comment by fivetran-joemarkiewicz** [comment]
@emiliedecherney After doing some digging I have been able to find that our package currently takes into consideration first reply time after an external comment is created. Taking a look at the screenshot you provided it looks like there has not been an external comment yet. Is that the case?

Additionally, do you see the nature of tickets commonly being created without a customer opening the ticket and creating a comment to be replied to? This is a type of functionality we do not have built into the package at the moment, but I would like to try and understand a bit better the nature of tickets that are not opened and first commented on by end users.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @emiliedecherney thanks for this confirmation. I also was able to find [Zendesk Support Metric Definitions](https://support.zendesk.com/hc/en-us/articles/360022182114#topic_cyq_fr4_l2b) and see how Zendesk is calculating these metrics on their end.
![image](https://user-images.githubusercontent.com/74217849/136976940-61a7d0d2-92c4-4def-af40-7efd488f1c91.png)

When we originally developed the code for the reply times in this package we followed the assumption that reply times would want to be measured following an end-user comment opposed to just the creation of the ticket. I would agree with you that in instances where an end-user creates a ticket but provides no comment then the measure will not be accurately recorded. Currently, we would like this package to replicate the definitions of these measures on Zendesk's side so our users will be able to replicate the same reports accurately.

I will make some adjustments on a branch and share in this thread so you may try and confirm if the results you are seeing are expected.

**Comment by fivetran-joemarkiewicz** [comment]
That would be great!

I will plan to do an audit of the metrics we originally had in the first iteration of this package. A few months ago we added a suite of metrics based off the definitions highlighted by Zendesk in the doc I shared above, but we did not revisit metrics we originally had in this package. This will be a good exercise to confirm those definitions align with what we have in the package.

**Comment by emiliedecherney** [comment]
Hi Joe,

I've tested with the updated package and reply times appear as expected!

I know you are also auditing other metrics against Zendesk's definitions.
To help with that, I did notice a few other metrics worth auditing:

   - total_agent_replies (With the latest package update, this matches more
   closely to what we were seeing when pulling directly from Zendesk, but does
   not align exactly)

For the tickets I validated against, the resolution and wait times in terms
of calendar minutes all tied out. But the same metrics in terms of business
minutes differed from what we saw when pulling from the Zendesk API. I am
wondering if there is a difference in how Zendesk classifies business
minutes vs. the Fivetran package?

   - first_resolution_business_minutes
   - full_resolution_business_minutes
   - requester_wait_time_in_business_minutes

Thank you!
Emilie

**Comment by emiliedecherney** [comment]
Thank you Joe.
Would you or someone at Fivetran be able to help us work through the dbt
upgrade? We've attempted this in the past but ran into issues.

Best,
Emilie

**Comment by fivetran-joemarkiewicz** [comment]
What types of issues had you run into in the past? Maybe I can help point you in the right direction here?!

**Comment by fivetran-joemarkiewicz** [comment]
@emiliedecherney sounds good! I was just doing some final tests before the package is released. 

One question I want to run by you. If when an agent opens a ticket for a customer and adds a comment at the same time of the ticket creation, but another public comment has not been made yet would you expect the reply time to be 0 or null?

I have done some digging into our own Zendesk data and see that Zendesk leaves these tickets as null instead of 0. Then the first reply time is made following the next public comment. To be consistent with Zendesk reporting I am leaning to keep those records as null, but was curious what your opinion is as the ticket you shared in the original issue looks to only have one public comment made to it.
