### ISSUE TITLE
Config variables values can't be found

### ISSUE THREAD

**Issue by unnelt** [fivetran/dbt_zendesk#6]
Good day

The package execution fails when it tries to execute models that have the following line (one such model is models/sla_policy/agent_work_time_breach/agent_work_time_business_hours_breached.sql):

{{ config(enabled=enabled_vars(['using_sla_policy','using_schedules'])) }}

I've tried to manually set these variables to 'true' in my project's dbt_project.yml file but the package still fails to run. I've also tried the below to no success still

vars:
  zendesk_source:
    using_schedules: true
    using_sla_policy: true
  zendesk:
    using_schedules: true
    using_sla_policy: true

Please kindly assist

**Comment by fivetran-kristin** [comment]
@unnelt thank you for creating an issue.  Can you please share a screenshot of the current version of your both your dbt_project.yml and your package.yml files? This will help me better figure out what's going on.

**Comment by unnelt** [comment]
Hi Kristin...My apologies for the late reply. Please find attached, on the left is the version from the dbt_project.yml file and on the right the same from the packages.yml file
![screenshot](https://user-images.githubusercontent.com/77478958/104907545-ec05dc80-598d-11eb-8627-b3c35fc7107a.png)

**Comment by fivetran-kristin** [comment]
@unnelt I tried to recreate this error, but had no luck.  Would you be open to scheduling some time for us to debug together?

You can book 15 minute mtgs with me using the following link: http://5tran.co/office-hours

**Comment by unnelt** [comment]
Hi @fivetran-kristin  I checked the calendar and the available slots translate to between 9pm and 10pm this side (GMT+2). That's fairly late actually. Any other suggestion you have please?

**Comment by fivetran-kristin** [comment]
@unnelt - perhaps can you send me a screen recording of all the steps you're making and the resulting error? Hopefully that'll be enough information to help.

**Comment by fivetran-kristin** [comment]
@unnelt just following up here.  We're you able to figure this out? If not, can you send over a video for me to help debug?

**Comment by unnelt** [comment]
Hi @fivetran-kristin  I was able to resolve this. I'll close the issue. My apologies for not keeping you posted. Thanks again for your assistance.
