### ISSUE TITLE
[Feature] ADD Databricks support to package

### ISSUE THREAD

**Issue by lucascrespo88** [fivetran/dbt_zendesk#72]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

Let the dbt package support a Databricks destination

### Are you interested in contributing this feature?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during your [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance.
- [X] No.

**Comment by fivetran-marioamaya** [comment]
Prospect Kueski is very interested in leveraging this package for their Databricks based deployment

**Comment by fivetran-joemarkiewicz** [comment]
Hi All, I just wanted to share an update that our team is currently working to make the package compatible with Databricks! You should see a release next week to support Databricks.

**Comment by fivetran-jamie** [comment]
released with v0.9.0!
