### ISSUE TITLE
[Bug] failures on dbt run on big zendesk schema

### ISSUE THREAD

**Issue by nbenezri** [fivetran/dbt_zendesk#76]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

The table `zendesk__ticket_field_history`  and `zendesk__ticket_metrics` are not able to incrementally refresh due to size.

When I run dbt run on zendesk package from fivetran I get the log below. it fails on those two tables as they are too big and consume too much resources until refshift can't hold it anymore.

Is there any way I can tune it? 

### Relevant error log or model output

```shell
13:24:06  Completed with 2 errors and 0 warnings:
13:24:06  
13:24:06  Database Error in model zendesk__ticket_field_history (models/zendesk__ticket_field_history.sql)
13:24:06    Query (3528505) cancelled by WLM abort action of Query Monitoring Rule "Max_Query_Mem_On_Disk".
13:24:06    DETAIL:  
13:24:06      -----------------------------------------------
13:24:06      error:  Query (3528505) cancelled by WLM abort action of Query Monitoring Rule "Max_Query_Mem_On_Disk".
13:24:06      code:      1078
13:24:06      context:   Query (3528505) cancelled by WLM abort action of Query Monitoring Rule "Max_Query_Mem_On_Disk".
13:24:06      query:     0
13:24:06      location:  wlm_query_action.cpp:156
13:24:06      process:   wlm [pid=25731]
13:24:06      -----------------------------------------------
13:24:06    compiled SQL at target/run/zendesk/models/zendesk__ticket_field_history.sql
13:24:06  
13:24:06  Database Error in model zendesk__ticket_metrics (models/zendesk__ticket_metrics.sql)
13:24:06    Query (3529173) cancelled by WLM abort action of Query Monitoring Rule "Max_Query_Mem_On_Disk".
13:24:06    DETAIL:  
13:24:06      -----------------------------------------------
13:24:06      error:  Query (3529173) cancelled by WLM abort action of Query Monitoring Rule "Max_Query_Mem_On_Disk".
13:24:06      code:      1078
13:24:06      context:   Query (3529173) cancelled by WLM abort action of Query Monitoring Rule "Max_Query_Mem_On_Disk".
13:24:06      query:     0
13:24:06      location:  wlm_query_action.cpp:156
13:24:06      process:   wlm [pid=25731]
13:24:06      -----------------------------------------------
13:24:06    compiled SQL at target/run/zendesk/models/zendesk__ticket_metrics.sql
```

### Expected behavior

To be able to create and incrementally refresh those tables.

### dbt Project configurations

models:
  fivetran_dbt:
  zendesk:
    +schema: 
    intermediate:
      +schema: 
    sla_policy:
      +schema: 
    ticket_history:
      +schema: 
  zendesk_source:
    +schema: 

vars:
  using_schedules: False
  zendesk_source:
    zendesk_database: dkall
    zendesk_schema: zendesk
  zendesk:
    ticket_field_history_extension_months: 6

### Package versions

packages:
  - package: fivetran/zendesk_source
    version: [">=0.6.0", "<0.7.0"]

  - package: fivetran/zendesk
    version: [">=0.8.0", "<0.9.0"]

### What database are you using dbt with?

redshift

### dbt Version

Core:
  - installed: 1.1.0
  - latest:    1.1.0 - Up to date!

Plugins:
  - postgres: 1.1.0 - Up to date!
  - redshift: 1.1.0 - Up to date!

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @nbenezri this is really interesting as I haven't seen this error occur with the Zendesk package previously 🤔 

Would you be open to sharing the approximate volume of your Zendesk ticket data? We do have a variable in place that will allow you to restrict the time frame in years for tickets (the default is 10 years). 

If you are only concerned about the recent years tickets, then you can limit this variable defined [here](https://github.com/fivetran/dbt_zendesk#extending-and-limiting-the-ticket-field-history) to just the past few years. This may help reduce the size of the operation.

Let me know if this helps!

**Comment by fivetran-joemarkiewicz** [comment]
Hey @nbenezri,

The `ticket_field_history_extension_months` variable actually creates more data. In a sense it will extend the ticket historical data by the variable (default is 1 month) to capture any changes within the ticket after it is closed. 

I would actually suggest removing this variable and instead just using `ticket_field_history_timeframe_years` and setting to 1 year.

**Comment by nbenezri** [comment]
That cleared one table from failing out. But one is still failing.

```
05:43:19  33 of 52 ERROR creating incremental model cdp.zendesk__ticket_field_history .... [ERROR in 743.72s]
05:43:19  50 of 52 START table model cdp.zendesk__sla_policies ........................... [RUN]
05:43:20  50 of 52 OK created table model cdp.zendesk__sla_policies ...................... [SELECT in 1.88s]
05:43:20  51 of 52 SKIP relation cdp.zendesk__ticket_backlog ............................. [SKIP]
05:44:20  49 of 52 OK created table model cdp.zendesk__ticket_metrics .................... [SELECT in 281.01s]
05:44:20  52 of 52 START table model cdp.zendesk__ticket_summary ......................... [RUN]
05:44:22  52 of 52 OK created table model cdp.zendesk__ticket_summary .................... [SELECT in 1.72s]
05:44:22  
05:44:22  Finished running 12 view models, 37 table models, 3 incremental models, 1 hook in 931.86s.
05:44:22  
05:44:22  Completed with 1 error and 0 warnings:
05:44:22  
05:44:22  Database Error in model zendesk__ticket_field_history (models/zendesk__ticket_field_history.sql)
05:44:22    Query (3562469) cancelled by WLM abort action of Query Monitoring Rule "Max_Query_Mem_On_Disk".
05:44:22    DETAIL:  
05:44:22      -----------------------------------------------
05:44:22      error:  Query (3562469) cancelled by WLM abort action of Query Monitoring Rule "Max_Query_Mem_On_Disk".
05:44:22      code:      1078
05:44:22      context:   Query (3562469) cancelled by WLM abort action of Query Monitoring Rule "Max_Query_Mem_On_Disk".
05:44:22      query:     0
05:44:22      location:  wlm_query_action.cpp:156
05:44:22      process:   wlm [pid=25731]
05:44:22      -----------------------------------------------
05:44:22    compiled SQL at target/run/zendesk/models/zendesk__ticket_field_history.sql
05:44:22  

```

<img width="1497" alt="image" src="https://user-images.githubusercontent.com/82036810/173502628-2768aa87-9ab9-4067-935a-5b4e5181db30.png">

**Comment by nbenezri** [comment]
running `dbt run --full-refresh` sorted the issue. I figured I needed that after the change in `dbt_project.yml`.
