### ISSUE TITLE
Additional fields required in the ticket_metrics model

### ISSUE THREAD

**Issue by unnelt** [fivetran/dbt_zendesk#8]
Hi

Will you kindly include the below fields in the ticket_metrics model of the dbt package?

•	assigned_at
•	assignee_stations
•	assignee_updated_at
•	group_stations
•	initially_assigned_at
•	last_comment_added_at
•	replies
•	reopens
•	requester_updated_at
•	status_updated_at
•	agent_wait_time_in_minutes__business
•	agent_wait_time_in_minutes__calendar
•	reply_time_in_minutes__business
•	reply_time_in_minutes__calendar

Thank you

**Comment by fivetran-kristin** [comment]
Hey @unnelt, thanks for the request. We'll work on getting these added during our next sprint. You can expect this to be ready by mid-Feb :) 

In the meantime, I have a few questions for you:
• assigned_at - do you want when the ticket was first assigned, or last assigned?
• assignee_stations - just researched this and it looks like "assignee stations" is the number of assignees that have been assigned to a ticket.  Does that align with your understanding?
• assignee_updated_at - This will be the last time an assignee change has been made, right?
• group_stations - Similar to assignee_stations,  this is the number of groups a ticket has been assigned to. Please confirm.
• replies - Do you want the count of replies made by the requester, as well as the count of replies made by the assignee?

The metrics requested below are currently in the package, and available in the `zendesk_ticket_metrics` table.  Please take a look and confirm you have access.
• agent_wait_time_in_minutes__business
• agent_wait_time_in_minutes__calendar
• reply_time_in_minutes__business (we have both first & total in the package)
• reply_time_in_minutes__calendar (we have both first & total in the package)

**Comment by unnelt** [comment]
Hi @fivetran-kristin thanks for your reply. My colleague who is able to answer your first set of questions (as she has more business knowledge around Zendesk data) is on leave and will only be back on Monday. I'll forward your query to her and we'll provide feedback as soon as she's back to the office.

With regards to your second question, I'm only able to find the fields that end with '_calendar' in the zendesk_ticket_metrics table.

**Comment by unnelt** [comment]
Hi @fivetran-kristin I was able to find answers to your first set of questions. Please see below:

• assigned_at - do you want when the ticket was first assigned, or last assigned? **Answer: This is the last assigned, there is another field initially_assigned_at which contains the first timestamp of assignment.**
• assignee_stations - just researched this and it looks like "assignee stations" is the number of assignees that have been assigned to a ticket. Does that align with your understanding? **Answer: This is correct**
• assignee_updated_at - This will be the last time an assignee change has been made, right? **Answer: This  is the time the last update was made by the assignee**
• group_stations - Similar to assignee_stations, this is the number of groups a ticket has been assigned to. Please confirm. **Answer: This is correct**
• replies - Do you want the count of replies made by the requester, as well as the count of replies made by the assignee? **Answer: This is the count of replies made by the assignee**

**Comment by fivetran-kristin** [comment]
Thanks, @unnelt! We are currently in the process of working on this.  We'll update this issue once the fields have been added.

**Comment by fivetran-kristin** [comment]
Hi @unnelt, thanks for your patience here! We've updated the package, and our latest package version contains all of the requested fields.

Please note a few things:
1. You will need to upgrade your package to version 0.2.0. You will be able to do this, once this update is pushed to dbt's hub (I expect it will be pushed in the next 12-24 hours.  You can check [this page](https://hub.getdbt.com/fivetran/zendesk/latest/) to see when version 0.2.0 is listed under the "Installation" section.
2. This release contains breaking changes, so please make yourself aware of those by reading the package updates [here](https://github.com/fivetran/dbt_zendesk/releases/tag/v0.2.0) prior to upgrading.


For your reference, I created this table for you to help navigate where you can find the fields you need.
request | dbt package field
-- | --
assigned_at | zendesk__ticket_metrics.last_agent_assignment_date
assignee_stations | zendesk__ticket_metrics.assignee_stations_count
assignee_updated_at | zendesk__ticket_metrics.assignee_ticket_last_update_at  zendesk__ticket_enriched.assignee_ticket_last_update_at
group_stations | zendesk__ticket_metrics.group_stations_count
initially_assigned_at | zendesk__ticket_metrics.first_agent_assignment_date
last_comment_added_at | zendesk__ticket_metrics.ticket_last_comment_date
replies | zendesk__ticket_metrics.total_agent_replies or zendesk__ticket_metrics.total_comments
reopens | zendesk__ticket_metrics.count_reopens
requester_updated_at | zendesk__ticket_metrics.requester_ticket_last_update_at zendesk__ticket_enriched.requester_ticket_last_update_at
status_updated_at | zendesk__ticket_metrics.last_status_assignment_date
agent_wait_time_in_minutes__business | zendesk__ticket_metrics.agent_wait_time_in_business_minutes
agent_wait_time_in_minutes__calendar | zendesk__ticket_metrics.agent_wait_time_in_minutes__calendar
reply_time_in_minutes__business | zendesk__ticket_metrics.reply_time_in_minutes__business
reply_time_in_minutes__calendar | zendesk__ticket_metrics.reply_time_in_minutes__calendar

**Comment by unnelt** [comment]
Hi @fivetran-kristin 

Thanks for the above feedback. Much appreciated. I've checked the dbt hub and it shows that the latest version of the package is still 0.1.1. Do you have any idea as to when they'd perhaps release version 0.2.0 you referred to above?

Teddy

**Comment by fivetran-joemarkiewicz** [comment]
Hi @unnelt I was keeping an eye on the dbt hub yesterday and noticed they didn't update it until mid day CST. If you check again you should be able to see v0.2.0 of the [zendesk](https://hub.getdbt.com/fivetran/zendesk/latest/) and [zendesk_source](https://hub.getdbt.com/fivetran/zendesk_source/latest/) packages are now live on the hub.

**Comment by unnelt** [comment]
Hi @fivetran-joemarkiewicz thanks for this. We had also been advised of this and were updated as soon as the packages went live on the hub...Thanks

**Comment by unnelt** [comment]
Hi @fivetran-kristin & team..thank you guys very much for assisting in getting this issue resolved. It's much appreciated. We now have all the Zendesk ticket_metrics we need for our analytics.
