### ISSUE TITLE
[Bug] Cannot compile models until they have been run

### ISSUE THREAD

**Issue by tim-summerton-brier** [fivetran/dbt_zendesk#89]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

When trying to compile a project using this package, in `int_zendesk__ticket_schedules` it tries to fetch a `default_schedule_id` from the materialised data. If you have not already run the models then the table it tries to fetch this from does not exist, and you get an error.

### Relevant error log or model output

```shell
Runtime Error
  Runtime Error in model int_zendesk__ticket_schedules (models/intermediate/int_zendesk__ticket_schedules.sql)
    404 Not found: Table <gcp_project>:_zendesk_source.stg_zendesk__schedule was not found in location EU
```

### Expected behavior

The models successfully compile without any of the data this package generates already being in place.

### dbt Project configurations

No special configuration. I can reproduce this with a fresh project generated by `dbt init`

### Package versions

0.10.0

### What database are you using dbt with?

bigquery

### dbt Version

Core:
  - installed: 1.4.4
  - latest:    1.4.4 - Up to date!

Plugins:
  - bigquery: 1.4.1 - Up to date!

### Additional Context

The code which creates the error is here
https://github.com/fivetran/dbt_zendesk/blob/v0.10.0/models/intermediate/int_zendesk__ticket_schedules.sql#L26-L44

It is wrapped in an `{% if execute %}`, which I assumed would prevent this from running during a `dbt compile`, but this does not appear to be working.

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [X] No.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @tim-summerton-brier thanks for opening this issue. We actually saw a similar issue a few weeks ago regarding the date_spine model having the same issue.

Thank you for investigating this and calling out the problematic lines. I believe if we change the following line to use a source call as opposed to a reference, then that should do the trick!

https://github.com/fivetran/dbt_zendesk/blob/1c7d4fc263a6fcad8f3210918edfc8b9ef0dfe35/models/intermediate/int_zendesk__ticket_schedules.sql#L33

I can have a version available to you in a few minutes to try and see if this edit addresses the issue you are facing.

**Comment by fivetran-joemarkiewicz** [comment]
@tim-summerton-brier, as I am looking into this a bit more I am realizing that changing this to be a source reference would not work for all our users. Reason being is that the ticket_schedule table is only created if an account is using multiple schedules. Therefore, an account could have the schedules turned on, but not have this source.

We currently account for this by creating an [empty tmp model](https://github.com/fivetran/dbt_zendesk_source/blob/main/models/tmp/stg_zendesk__ticket_schedule_tmp.sql) if there is only one schedule. As such, we would need to reference the created model for most cases as opposed to the source. 🤔 

I will keep thinking through this and will get back to you with any other thoughts or solutions as opposed to just running the package before compiling.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @tim-summerton-brier I was able to implement a hot fix to resolve the core issue you identified. When you have a moment, would you be able to try the following version of the package in your `packages.yml`?

```yml
packages:
  - git: https://github.com/fivetran/dbt_zendesk.git
    revision: hotfix/schedule-source-adjustment
    warn-unpinned: false 
```

You can use the above in place of the official version of the zendesk package. Let me know if you are able to `dbt compile` using this version. Thanks!

**Comment by tim-summerton-brier** [comment]
Hi @fivetran-joemarkiewicz 
That hotfix version is working for me, I can now compile with no issue. Thanks!
When can we expect the hotfix to be available in the official release?

**Comment by fivetran-joemarkiewicz** [comment]
That is great to hear!

I will open the PR today and you can expect the release to be live most likely early next week.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @tim-summerton-brier thanks again for raising this to our team. The PR has since been merged and is live on the latest version of the package!

As such, I will close out this issue. Please feel free to reopen if the original issue persists.
